-- daily_weather is now a fact table (no location_name/lat/lon).
-- Join to DIM_LOCATION to get back the human-readable name and coords.
SELECT dl.LOCATION_NAME, dw.WEATHER_DATE, dl.LATITUDE, dl.LONGITUDE,
       dw.HOURS_RECORDED, dw.AVG_TEMPERATURE_F, dw.MIN_TEMPERATURE_F, dw.MAX_TEMPERATURE_F,
       dw.AVG_HUMIDITY_PCT, dw.TOTAL_PRECIPITATION_IN, dw.AVG_WIND_SPEED_MPH, dw.MAX_WIND_SPEED_MPH
FROM WEATHER_DB.WEATHER_DBT.DAILY_WEATHER dw
INNER JOIN WEATHER_DB.WEATHER_DBT.DIM_LOCATION dl USING (LOCATION_ID);



SELECT ID, RECORDED_AT, LOCATION_NAME, LATITUDE, LONGITUDE, TEMPERATURE_F, HUMIDITY_PCT, PRECIPITATION_IN, WIND_SPEED_MPH, WEATHER_CODE, LOADED_AT
FROM WEATHER_DB.WEATHER.WEATHER_HOURLY;




--499
--2,455
SELECT COUNT(*)
FROM WEATHER_DB.WEATHER_DBT.DAILY_WEATHER;

--58,920
SELECT COUNT(*)
FROM WEATHER_DB.WEATHER.WEATHER_HOURLY;



-- Hourly facts decorated with their parent day's aggregates AND location attributes.
-- Three-way join: hourly fact ── (location_name) ── dim ── (location_id) ── daily fact.
-- Note daily_weather no longer carries location_name/lat/lon — we get them from dim.
SELECT
    dl.LOCATION_NAME, wd.WEATHER_DATE, wh.RECORDED_AT, dl.LATITUDE, dl.LONGITUDE,
    wd.AVG_TEMPERATURE_F      AS DAILY_AVG_TEMPERATURE_F,
    wd.MIN_TEMPERATURE_F      AS DAILY_MIN_TEMPERATURE_F,
    wd.MAX_TEMPERATURE_F      AS DAILY_MAX_TEMPERATURE_F,
    wd.AVG_HUMIDITY_PCT       AS DAILY_AVG_HUMIDITY_PCT,
    wd.TOTAL_PRECIPITATION_IN AS DAILY_TOTAL_PRECIPITATION_IN,
    wd.AVG_WIND_SPEED_MPH     AS DAILY_AVG_WIND_SPEED_MPH,
    wd.MAX_WIND_SPEED_MPH     AS DAILY_MAX_WIND_SPEED_MPH,
    wh.ID AS HOURLY_ID, wh.TEMPERATURE_F, wh.HUMIDITY_PCT, wh.PRECIPITATION_IN,
    wh.WIND_SPEED_MPH, wh.WEATHER_CODE, wh.LOADED_AT
FROM WEATHER_DB.WEATHER.WEATHER_HOURLY wh
INNER JOIN WEATHER_DB.WEATHER_DBT.DIM_LOCATION dl
    ON wh.LOCATION_NAME = dl.LOCATION_NAME
INNER JOIN WEATHER_DB.WEATHER_DBT.DAILY_WEATHER wd
    ON  wd.LOCATION_ID  = dl.LOCATION_ID
    AND CAST(wh.RECORDED_AT AS DATE) = wd.WEATHER_DATE
ORDER BY dl.LOCATION_NAME, wd.WEATHER_DATE, wh.RECORDED_AT;






SELECT COUNT(*)
FROM WEATHER_DB.WEATHER.WEATHER_HOURLY wh
INNER JOIN WEATHER_DB.WEATHER_DBT.DIM_LOCATION dl
    ON wh.LOCATION_NAME = dl.LOCATION_NAME
INNER JOIN WEATHER_DB.WEATHER_DBT.DAILY_WEATHER wd
    ON  wd.LOCATION_ID  = dl.LOCATION_ID
    AND CAST(wh.RECORDED_AT AS DATE) = wd.WEATHER_DATE;
